# This is a basic workflow to help you get started with Actions

name: GTFS DATECHECK

# Controls when the workflow will run
on:
  #schedule:
  #  - cron: '0 24 * * *'
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment:
      name: GITHUB_SECRETS

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      #- name: Install dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install -r requirements.txt
      - name: Run script
        run: |
          python gtfs-checkurl-zip.py
      - name: git settings
        run: |
          git config --global user.name "${{ secrets.SECRET_NAME }}"
          git config --global user.email "${{ secrets.SECRET_MAIL }}"
      - name: CSV commit
        run: |
          git add .
          git commit -m "Update csv file"
          git push origin main

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!
      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
